/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspkl;
import com.mysql.cj.protocol.Resultset;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.beans.binding.Bindings.isEmpty;
import static javafx.beans.binding.Bindings.isEmpty;
import static javafx.beans.binding.Bindings.isEmpty;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bill
 */
public class jDatatable1 extends javax.swing.JFrame {
static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
static final String DB_URL = "jdbc:mysql://localhost/cloudpos";
static final String USER = "root";
static final String PASS = "";
static String ps = "";


static Connection conn;
static Statement stmt;
static ResultSet rs;
    /**
     * Creates new form jDatatable
     */
    public jDatatable1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showdatabtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showdatabtn.setText("tbl_kab_kota");
        showdatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdatabtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jButton1.setText("tbl_kecamatan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("tbl_kelurahan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("tbl_provinsi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("insert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showdatabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showdatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void showdatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdatabtnActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        ps = "tbl_kab_kot";
        try{
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql ="SELECT * FROM tbl_kab_kot";
        rs = stmt.executeQuery(sql);
        
        while(rs.next()){
        String id_kabkot = String.valueOf(rs.getInt("id_kabkot"));
        String id_provinsi = String.valueOf(rs.getInt("id_provinsi"));
        String kab_kota = rs.getString("kab_kota");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id kabupaten kota");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(1).setHeaderValue("id provinsi");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(2).setHeaderValue("kabupaten kota");
        jTable1.getTableHeader().resizeAndRepaint();
        
        String []tbData = {id_kabkot,id_provinsi,kab_kota};        
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(tbData);
        }
        stmt.close();
        conn.close();
        }catch(Exception e){
        e.printStackTrace();
        }
           
    }//GEN-LAST:event_showdatabtnActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        ps="";
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        ps = "tbl_kecamatan";
        try{
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql ="SELECT * FROM tbl_kecamatan";
        rs = stmt.executeQuery(sql);
        
        while(rs.next()){
        String id_kecam = String.valueOf(rs.getInt("id_kecamatan"));
        String id_kab_kota = String.valueOf(rs.getInt("id_kab_kot"));
        String kecamatan = rs.getString("kecamatan");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id kecamatan");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(1).setHeaderValue("id kabupaten kota");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(2).setHeaderValue("kecamatan");
        jTable1.getTableHeader().resizeAndRepaint();
        
        String []tbData = {id_kecam,id_kab_kota,kecamatan};        
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(tbData);
        }
        stmt.close();
        conn.close();
        }catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        ps = "tbl_kelurahan";
        try{
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM tbl_kelurahan";
        rs = stmt.executeQuery (sql);
        
        while(rs.next()){
        String id_kelur = rs.getString("id_kelurahan");
        String id_kecam = rs.getString("id_kecamatan");
        String kelurahan = rs.getString("kelurahan");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id kelurahan");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.getColumnModel().getColumn(1).setHeaderValue("id kecamatan");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.getColumnModel().getColumn(2).setHeaderValue("kelurahan");
        jTable1.getTableHeader().resizeAndRepaint();
        
       String []tbData ={id_kelur,id_kecam,kelurahan};
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
       tblModel.addRow(tbData);
        }
        }catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(false);
        ps = "tbl_provinsi";
        try{
        Class.forName(JDBC_DRIVER);
        conn =DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM tbl_provinsi";
        rs = stmt.executeQuery(sql);
        while(rs.next()){
        String id_provinsi = String.valueOf(rs.getInt("id_provinsi"));
        String provinsi = rs.getString("provinsi");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id provinsi");
        jTable1.getTableHeader().resizeAndRepaint();       
        jTable1.getColumnModel().getColumn(1).setHeaderValue("provinsi");
        jTable1.getTableHeader().resizeAndRepaint();
       
        String []tbData = {id_provinsi,provinsi};
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(tbData);
        }
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (ps.equals("") ){
        JOptionPane.showMessageDialog(null,"pilih tabel terlebih dahulu");
        }
        if (ps.equals("tbl_kab_kot")){        
        try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        String sql = "INSERT INTO tbl_kab_kot values (?,?,?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));
        stmt.setInt(2,Integer.parseInt(jTextField2.getText()));
        stmt.setString(3,(jTextField3.getText()));
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"insert succesfull");
        conn.close();                
    } catch (Exception e) {        
        if(jTextField1.getText()!=("0") || jTextField2.getText() != ("0")){  
            JOptionPane.showMessageDialog(null,"masukan input terlebih dahulu");
        }else {
        JOptionPane.showMessageDialog(null,e);
        }
    }
        }
        if (ps.equals("tbl_kecamatan")){ 
        try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        String sql = "INSERT INTO tbl_kecamatan values (?,?,?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1,(jTextField1.getText()));
        stmt.setString(2,(jTextField2.getText()));
        stmt.setString(3,(jTextField3.getText()));
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"insert succesfull");
        conn.close();
    } catch (Exception e) {
        if(jTextField1.getText()!=("0") || jTextField2.getText() != ("0")){  
            JOptionPane.showMessageDialog(null,"masukan input terlebih dahulu");
        }else {
        JOptionPane.showMessageDialog(null,e);
        }
    
    }
        }
         if (ps.equals("tbl_kelurahan")){ 
        try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        String sql = "INSERT INTO tbl_kelurahan values (?,?,?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1,(jTextField1.getText()));
        stmt.setString(2,(jTextField2.getText()));
        stmt.setString(3,(jTextField3.getText()));
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"insert succesfull");
        conn.close();
    } catch (Exception e) {
        if(jTextField1.getText()!=("0") || jTextField2.getText() != ("0")){  
            JOptionPane.showMessageDialog(null,"masukan input terlebih dahulu");
        }else {
        JOptionPane.showMessageDialog(null,e);
        }
         }  
         }
         if (ps.equals("tbl_provinsi")){ 
        try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        String sql = "INSERT INTO tbl_provinsi values (?,?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));
        stmt.setString(2,(jTextField2.getText()));
                
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"insert succesfull");
        conn.close();
    } catch (Exception e) {
        if(jTextField1.getText()!=("0") || jTextField2.getText() != ("0")){  
            JOptionPane.showMessageDialog(null,"masukan input terlebih dahulu");
        }else {
        JOptionPane.showMessageDialog(null,e);
        }
    }
         } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        String sql = "UPDATE tbl_kab_kot SET id_provinsi =?,kab_kota=? WHERE id_kabkot =?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));
        stmt.setInt(2,Integer.parseInt(jTextField2.getText()));
        stmt.setString(3,(jTextField3.getText()));
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"Edit succesfull");
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (ps.equals("")){
        JOptionPane.showMessageDialog(null,"pilih tabel terlebih dahulu");
        }
        if (ps.equals("tbl_kab_kot")){ 
        try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "DELETE FROM tbl_kab_kot WHERE id_kabkot = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"delete succesfull");
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
        }
     if (ps.equals("tbl_kecamatan")){
     try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "DELETE FROM tbl_kecamatan WHERE id_kecamatan = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"delete succesfull");
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
     }   
     if (ps.equals("tbl_kelurahan")){
     try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "DELETE FROM tbl_kelurahan WHERE id_kelurahan = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"delete succesfull");
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
     }   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (ps.equals("tbl_kab_kot")){
        try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "SELECT * FROM tbl_kab_kot WHERE id_kabkot = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));  
        
        ResultSet rs = stmt.executeQuery();
        if(rs.next()){
        jTextField1.setText(rs.getString("id_kabkot"));
        jTextField2.setText(rs.getString("id_provinsi"));
        jTextField3.setText(rs.getString("kab_kota"));
        }
        else {
        JOptionPane.showMessageDialog(null,"data not found");
        }
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
        }
        if (ps.equals("tbl_kelurahan")){
        try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "SELECT * FROM tbl_kelurahan WHERE id_kelurahan = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));         
        ResultSet rs = stmt.executeQuery();
        if(rs.next()){
        jTextField1.setText(rs.getString("id_kelurahan"));
        jTextField2.setText(rs.getString("id_kecamatan"));
        jTextField3.setText(rs.getString("kelurahan"));
        }
        else {
        JOptionPane.showMessageDialog(null,"data not found");
        }
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
        }
        if (ps.equals("tbl_kecamatan")){
        try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "SELECT * FROM tbl_kecamatan WHERE id_kecamatan = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));         
        ResultSet rs = stmt.executeQuery();
        if(rs.next()){
        jTextField1.setText(rs.getString("id_kecamatan"));
        jTextField2.setText(rs.getString("id_kab_kot"));
        jTextField3.setText(rs.getString("kecamatan"));
        }
        else {
        JOptionPane.showMessageDialog(null,"data not found");
        }
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
        }
        if (ps.equals("tbl_provinsi")){
        try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);        
        String sql = "SELECT * FROM tbl_provinsi WHERE id_provinsi = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(jTextField1.getText()));         
        ResultSet rs = stmt.executeQuery();
        if(rs.next()){
        jTextField1.setText(rs.getString("id_provinsi"));        
        jTextField2.setText(rs.getString("provinsi"));
        }
        else {
        JOptionPane.showMessageDialog(null,"data not found");
        }
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDatatable1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDatatable1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDatatable1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDatatable1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jDatatable1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton showdatabtn;
    // End of variables declaration//GEN-END:variables
}
