/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspkl;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bill
 */
public class jDatatable extends javax.swing.JFrame {
static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
static final String DB_URL = "jdbc:mysql://localhost/cloudpos";
static final String USER = "root";
static final String PASS = "";


static Connection conn;
static Statement stmt;
static ResultSet rs;
    /**
     * Creates new form jDatatable
     */
    public jDatatable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showdatabtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showdatabtn.setText("tbl_kab_kota");
        showdatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdatabtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jButton1.setText("tbl_kecamatan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("tbl_kelurahan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("tbl_provinsi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showdatabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(showdatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void showdatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdatabtnActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
         jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        try{
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql ="SELECT * FROM tbl_kab_kot";
        rs = stmt.executeQuery(sql);
        
        while(rs.next()){
        String id_kabkot = String.valueOf(rs.getInt("id_kabkot"));
        String id_provinsi = String.valueOf(rs.getInt("id_provinsi"));
        String kab_kota = rs.getString("kab_kota");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id kabupaten kota");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(1).setHeaderValue("id provinsi");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(2).setHeaderValue("kabupaten kota");
        jTable1.getTableHeader().resizeAndRepaint();
        
        String []tbData = {id_kabkot,id_provinsi,kab_kota};        
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(tbData);
        }
        stmt.close();
        conn.close();
        }catch(Exception e){
        e.printStackTrace();
        }
           
    }//GEN-LAST:event_showdatabtnActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
         jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
         jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        try{
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql ="SELECT * FROM tbl_kecamatan";
        rs = stmt.executeQuery(sql);
        
        while(rs.next()){
        String id_kecam = String.valueOf(rs.getInt("id_kecamatan"));
        String id_kab_kota = String.valueOf(rs.getInt("id_kab_kot"));
        String kecamatan = rs.getString("kecamatan");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id kecamatan");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(1).setHeaderValue("id kabupaten kota");
        jTable1.getTableHeader().resizeAndRepaint();
        
        jTable1.getColumnModel().getColumn(2).setHeaderValue("kecamatan");
        jTable1.getTableHeader().resizeAndRepaint();
        
        String []tbData = {id_kecam,id_kab_kota,kecamatan};        
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(tbData);
        }
        stmt.close();
        conn.close();
        }catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
         jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        try{
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM tbl_kelurahan";
        rs = stmt.executeQuery (sql);
        
        while(rs.next()){
        String id_kelur = rs.getString("id_kelurahan");
        String id_kecam = rs.getString("id_kecamatan");
        String kelurahan = rs.getString("kelurahan");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id kelurahan");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.getColumnModel().getColumn(1).setHeaderValue("id kecamatan");
        jTable1.getTableHeader().resizeAndRepaint();
        jTable1.getColumnModel().getColumn(2).setHeaderValue("kelurahan");
        jTable1.getTableHeader().resizeAndRepaint();
        
       String []tbData ={id_kelur,id_kecam,kelurahan};
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
       tblModel.addRow(tbData);
        }
        }catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTable1.getColumnModel().getColumn(0).setHeaderValue("");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("");
        jTable1.getTableHeader().resizeAndRepaint();
         jTable1.setModel(new DefaultTableModel(null,new String[]{"","",""}));
        try{
        Class.forName(JDBC_DRIVER);
        conn =DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM tbl_provinsi";
        rs = stmt.executeQuery(sql);
        while(rs.next()){
        String id_provinsi = String.valueOf(rs.getInt("id_provinsi"));
        String provinsi = rs.getString("provinsi");
        
        jTable1.getColumnModel().getColumn(0).setHeaderValue("id provinsi");
        jTable1.getTableHeader().resizeAndRepaint();       
        jTable1.getColumnModel().getColumn(1).setHeaderValue("provinsi");
        jTable1.getTableHeader().resizeAndRepaint();
       
        String []tbData = {id_provinsi,provinsi};
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(tbData);
        }
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDatatable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDatatable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDatatable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDatatable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jDatatable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showdatabtn;
    // End of variables declaration//GEN-END:variables
}
